### PR TITLE
Sidebar questions

### PR DESCRIPTION
**Pull request by Podesta**
Complete fixes from 5704c7b adding the `EquivalentQuestionsInOtherNetworks`.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this contribution.

In future, please dont push revision bumps along with PR's, this is done by the person doing the reelase via automated methods like https://github.com/StylishThemes/Quora-Dark/commit/29e7d132fd2629c77cf5be7f385ebaf3acb2529a which also creates tags.

Ill merge this as is and adjuts later this time =)

Thanks again for fixes =) appreciated..

**Comment by Podesta** [comment]
Ok, my bad. You should probably update the `contributing.md`. Since it is the standard from the other stylish themes, and on the other projects it is recommended to bump the version number, and also add the authors (which I didn't do). But yeah, I did update it manually, since I don't have npm on this machine, another mistake of mine.

**Comment by the-j0k3r** [comment]
>Since it is the standard from the other stylish themes

I think its OK to add something in the contrib.md though, there's nothing asking for contributors to handle releases, its part of the development internally, its just not a parctice Im aware in any project.,

I apologize in advance if I come across as argumentative, just trying to be informative., 

 I'll add that to my todo list as we have quite a few and they are outdated in the development scripts area where we have replaced the semver with ver.

Thanks again.

**Comment by Podesta** [comment]
No problem.  Just to clarify, I absolutely take no offense, and actually appreciate you taking your time to let me know that I made a mistake. If I'm coming across as argumentative, questioning or anything, I also apologize, since that is far from my intention. You are not discouraging me from helping in the future or anything of the sort. I see this solely as you letting me know I made a mistake (to which I accept and apologize for), and explaining why I made that mistake, a completely normal interaction. There is nothing for you to be worried on my end.

Re reading the contributing, you are correct, there is no recommendation to bump the version number (although it does recommend to use the authors tool). I guess I came to that conclusion since It was a recommendation I received in one of the PR's I did for another style from you guys.

Just as clarification. Was my mistake bumping the version manually, instead of using the npm tools, or should I never add the commits generated by `npm run authors` and `npm run patch` as part of a PR, and instead leave it to one of the maintainers?

**Comment by the-j0k3r** [comment]
> Just as clarification. Was my mistake bumping the version manually, instead of using the npm tools, or should I never add the commits generated by `npm run authors` and `npm run patch` as part of a PR, and instead leave it to one of the maintainers?

Yes, short answer for now, but dont be too hard on yourself, I think the Contribution.md could be clearer. also

I started an internal team discussion to see how best proceed with this.

Thanks again.

**Comment by Podesta** [comment]
Ok, so I went over to understand where I had the idea to bump the version number. 

It comes from [this PR on the discourse style](https://github.com/StylishThemes/Discourse-Dark/pull/11). By that point I already had a handful of commits, and was already invited as collaborator, so that's likely the reason why Mottie recommended me to use to tools.

I guess the bottom line is that it was a series of misunderstandings on my end. Maybe the contributing could be more explicit, but if that's not a problem you guys had to deal in the past (except from me), then it's more likely that the file is actually fine and I misinterpreted it.

**Comment by the-j0k3r** [comment]
Thats OK, Once we discussed whats what I'll definitely update the contribution.md with clearer guidelines, so no new future people in team get confused either.

Thanks again and have a great weekend.  =)

**Comment by the-j0k3r** [comment]
@Podesta in process of updating contributing.md

They all more or less say the same (except those Ive not updated yet)
e.g. https://github.com/StylishThemes/Quora-Dark/commit/bfa52c57f1cc504f7108af81d2a42d9146fa22a9

**Comment by Podesta** [comment]
Thanks! Hopefully it will help future contributors.

**Pull request merged**
