### PR TITLE
Darken cookie banner and 'Still have a question?' popup...

### PR DESCRIPTION
**Pull request by danielmizrachi**
...make 'Ask' buttons consistently red and their text readable.

This is a minor improvement on 30c65b0a30b7f9c239f5ed29f03b9cdf4d064bf6, with the cookie banner improvement too.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @danielmizrachi!

Thanks for your contribution! I haven't seen the cookie banner, or maybe I haven't looked lately, so thank you for providing a fix.

I am concerned about using the id selector that starts out with `#__w2_` followed by apparently random letters... I've seen them too, but I wonder if they are consistent. Is there a class associated with that button, I would prefer to use it instead?

**Comment by danielmizrachi** [comment]
@Mottie thanks for a quick response!

The cookie banner currently looks [like this](https://i.imgur.com/PYL4msm.png), and I can understand how it's been overlooked being a one-time appearance.

As for the selected ID, my apologies for not being careful; it appears elements' IDs are partially random on a per session basis from what I can tell. By the looks of it, this particular button could be reliably selected with `a.LoggedOutAskQuestionInput.LoggedOutAskQuestionButton.AskQuestionInput.AskQuestionButton`... obviously this is cumbersome and could inadvertently modify other buttons, but unless you know about other elements that these individual classes are being applied to, this is probably the best option.

Let me know and I'll push the relevant changes. 😄

**Comment by Mottie** [comment]
We don't need to worry too much about the length of the selector, but I noticed that there is an instance of the `.AskQuestionButton` selector in the style, but it's preceded by another selector ([ref](https://github.com/StylishThemes/Quora-Dark/blob/master/quora-dark.css#L73)). Maybe we only need to add `.AskQuestionButton`? Please test and add the appropriate specificity of selectors if that one selector isn't good enough.

**Comment by Mottie** [comment]
Awesome, thanks!!

**Pull request merged**
